apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
images:
- name: quarkus-demo
  newName: sookeke/quarkus-github-actions-demo
  newTag: "58"
